inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: percent
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/BlockLength:
  Max: 150
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 10
AllCops:
  NewCops: enable